swagger: "2.0"
info:
  version: 1.0.0
  title: Simulation API
  description: An API for managing simulations within 3DSIM.  
  termsOfService: https://3dsim.com
  contact:
    name: 3DSIM API Team
    email: support@3dsim.com
    url: https://3dsim.github.io
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: 3dsim.cloud.tyk.io
basePath: /simulation-api
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /status:
    get:
      description: |
        Use this endpoint to check server status.
      operationId: status
      responses:
        200:
          description: status response
          schema:
            $ref: '#/definitions/Status'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Status:
    properties:
      status: 
        type: string
        default: okay
        enum:
          - okay
          - problem
          - slow
      message:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string